# Generated by Django 4.2.25 on 2025-10-19 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workers", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="worker",
            options={"verbose_name": "работник", "verbose_name_plural": "работники"},
        ),
        migrations.AlterField(
            model_name="worker",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_workers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кем создан",
            ),
        ),
        migrations.AlterField(
            model_name="worker",
            name="first_name",
            field=models.CharField(max_length=150, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="worker",
            name="hired_date",
            field=models.DateField(
                auto_now_add=True, verbose_name="Дата приёма на работу"
            ),
        ),
        migrations.AlterField(
            model_name="worker",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AlterField(
            model_name="worker",
            name="last_name",
            field=models.CharField(max_length=150, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="worker",
            name="middle_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="Отчество"),
        ),
        migrations.AlterField(
            model_name="worker",
            name="position",
            field=models.CharField(max_length=254, verbose_name="Должность"),
        ),
        migrations.AlterField(
            model_name="worker",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата последнего обновления"
            ),
        ),
    ]
